project:
  type: website
  output-dir: docs

website:
  title: "Dominik G. Eichhorn"
  favicon: inputs/logo.png
  navbar:
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: CV
        href: inputs/resume.pdf
      - text: Other Stuff
        href: projects.qmd
      - text: Coding/Projects
        href: blog/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



