project:
  type: website
  output-dir: docs

website:
  title: "Dominik G. Eichhorn"
  favicon: inputs/logo.png
  navbar:
    background: "#0b0b64"
    foreground: "white"
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - text: About me
        href: about.qmd
      - text: CV
        menu:
          - text: EN
            href: inputs/CV_DominikEichhorn.pdf
          - text: DE
            href: inputs/Lebenslauf_DominikEichhorn.pdf
      - text: Coding
        href: coding/index.qmd

format:
  html:
    theme: cosmo
    linkcolor: "#0b0b64"
    css: styles.css
    toc: true



