project:
  type: website
  output-dir: docs

website:
  title: "Dominik G. Eichhorn"
  favicon: inputs/logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



